version: '3.8'

services:
  db:
    image: postgres:16
    container_name: electrohub-db
    restart: always
    environment:
      POSTGRES_USER: electrohub
      POSTGRES_PASSWORD: electrohub123
      POSTGRES_DB: electrohub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
